name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with: 
          php-version: '8.3'
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest
          php $GITHUB_WORKSPACE/vendor/bin/phpcs --config-set severity 8
      - name: Run PHPMD
        run: $GITHUB_WORKSPACE/vendor/bin/phpmd src text cleancode,codesize
      - name: Run PHPCS
        run: $GITHUB_WORKSPACE/vendor/bin/phpcs --standard=PSR12 src
